------ Basic queries ------

## Active customers and info
select * from customers where status='Active';

##  What is the total Budgeted_revenue and expense for the entire company in the year 2022 and 2023?
select year, sum(budgeted_revenue) as estimated_revenue, sum(budgeted_expense) as Estimated_Expense
from budget group by year;

## generate a unique list of all the different Category types that our vendors belong to?
select category, count(vendor_id) as Total_vendors from vendors group by category order by Total_vendors desc;

## Find the top 10 largest financial transactions (highest Amount), displaying the Transaction_date, Amount, and Account_type
select transaction_date, amount, account_type from financial_transactions order by amount desc limit 10;

## What is the total sum of Amount spent per Vendor_name? 
select v.vendor_id, v.vendor_name, round(sum(f.amount),2) as amount_spent from vendors as v left join financial_transactions as f on
f.vendor_id = v.vendor_id group by v.vendor_id, v.vendor_name order by amount_Spent desc;

## Which Region has more than 10 active customers?
select region, count(customer_id) as total_customers from customers where status = 'Active'
group by region having total_customers > 50;

## For all Business_unit, calculate the total actual Revenue and the total actual Expense?
select business_unit, Account_type, round(sum(amount),2) as total from financial_transactions where 
Account_type in ('Revenue', 'Expense') group by business_unit, Account_type;

## What is the average Cost_to_company for employees in each Region
select region, round(avg(cost_to_company),2) as Avg_CTC from headcount group by region;

## Are there any vendors listed in the Vendors table that do not have a single transaction recorded in the Financial_Transactions table?
select * from vendors where vendor_id not in (select vendor_id from financial_transactions);

## Calculate the total revenue generated by each customer segment
select c.segment, round(sum(f.amount),2) as total_amount from customers as c join
 financial_transactions as f on c.Customer_id=f.Customer_id  where f.account_type= 'Revenue' group by c.segment;

#1. What is the total number of active employees and the average 'Cost_to_company' for each Business Unit?
select count(employee_id) as total_active_employees from headcount where Status = 'Active';
select business_unit, count(Employee_id) as total_emp, round(avg(cost_to_company),2) as Average_CTC from headcount
 WHERE STATUS = 'Active' group by business_unit order by Average_CTC desc;

#2. How many customers are currently 'Active' versus 'Inactive', broken down by Region?
select region, status, count(customer_id) as total_customers from customers group by region, status
order by total_customers desc;

#3. What are the top 5 expense categories by total transaction amount?
select category, round(sum(Amount),2) as total_amount from financial_transactions
group by category order by total_amount desc limit 5; 

#4. Which customers have generated more than $250,000 in total revenue but are currently marked as 'Inactive' in the Customers table?
select financial_transactions.customer_id, customers.customer_name, sum(financial_transactions.Amount) as total_Amount from
financial_transactions join customers on financial_transactions.customer_id=customers.Customer_id
where customers.Status='Inactive' group by financial_transactions.Customer_id, customers.customer_name having total_amount > 250000;

#5. Which 10 vendors received the highest total payout in 2023, and what is their corresponding category and region?
SET SQL_SAFE_UPDATES = 0;
Update financial_transactions set Transaction_date= STR_TO_DATE(Transaction_date, "%m/%d/%YYYY");

select financial_transactions.Vendor_id, vendors.Vendor_name, vendors.Category, vendors.Region, 
abs(round(sum(financial_transactions.Amount),2))as total_amount from financial_transactions join
vendors on financial_transactions.Vendor_id = vendors.Vendor_id where 
year(financial_transactions.transaction_date) = 2023 group by financial_transactions.Vendor_id,
vendors.Vendor_name, vendors.Category, vendors.Region order by total_amount desc limit 10;

# 6. What is the net profit (Total Revenue - Total Expense) for each region yearly?
select year(transaction_date) as Year, region, round(sum(Amount),2) as net_profit from
 financial_transactions group by year, region order by region desc;
 
# 7. For each Business Unit, what is the ratio of Total Actual Revenue generated to the Total 'Cost_to_company' of all active employees?
select r.Business_unit, r.revenue, h.total_CTC, round(r.revenue/h.total_CTC) as revenue_to_CTC from 
(select Business_unit, round(sum(Amount),2) as Revenue from financial_transactions where Account_type='Revenue'
 group by business_unit) r join (select business_unit, sum(cost_to_company) as total_CTC from headcount
 where status ='Active' group by business_unit)h on r.business_unit = h.business_unit;


# 9. Calculate the total revenue generated by each customer. Then, use a window function to 
# rank the top 3 highest-revenue customers within each customer segment (Retail, Enterprise, Online) 
WITH Customer_Revenue AS (
SELECT c.Customer_id, c.Customer_name, c.segment, SUM(f.Amount) AS Total_Revenue
FROM Customers c JOIN Financial_Transactions f ON c.Customer_id = f.Customer_id
WHERE f.Account_type = 'Revenue'GROUP BY c.Customer_id, c.Customer_name, c.segment),
Ranked_Customers AS (
SELECT Customer_id, Customer_name, segment, Total_Revenue,
RANK() OVER (PARTITION BY segment ORDER BY Total_Revenue DESC) as Revenue_Rank
FROM Customer_Revenue)
SELECT Customer_id, Customer_name, segment, Total_Revenue, Revenue_Rank
FROM Ranked_Customers WHERE Revenue_Rank <= 3
ORDER BY segment ASC, Revenue_Rank ASC;

## 10. budgeted revenue v/s actual revenue
select round(sum(b.budgeted_revenue),2) as budgeted_revenue, round(sum(f.amount),2) as actual_revenue
from budget as b join financial_transactions as f on b.Business_unit = f.Business_unit where f.account_type ='Revenue';
select sum(budgeted_revenue), sum(budgeted_expense) from budget;

## 11. Actual expense v/s budgeted expense
select account_type, sum(amount) as actual from financial_transactions group by account_type;

## Budget for particular business unit
select business_unit, round(sum(budgeted_revenue),2) as est_revenue, round(sum(budgeted_expense),2) as est_expense
from budget group by business_unit;

## actual revenue and expense of all business units
select business_unit, account_type, round(sum(amount),2) from financial_transactions where 
account_type in ('Revenue','Expense') group by business_unit, account_type;

## actual revenue and expense of all categoriess
select Category, account_type, round(sum(amount),2) as actual_cost from financial_transactions where 
account_type in ('Revenue','Expense') group by category, account_type order by actual_cost;

## region wise revenue and expense
select region, account_type, round(sum(amount),2) as actual_cost from financial_transactions where 
account_type in('Revenue','Expense') group by region, account_type order by actual_cost;

## ctc v/s payroll
select h.business_unit, sum(h.cost_to_company) as total_CTC, round(sum(abs(f.Amount)),2) As Payroll from headcount as h join 
financial_transactions as f on h.business_unit = f.business_unit where f.category = 'Payroll' group by h.business_unit;

select sum(h.cost_to_company) as total_CTC, round(sum(abs(f.Amount)),2) As Payroll from headcount as h join 
financial_transactions as f on h.business_unit = f.business_unit where f.category = 'Payroll';

###  Top 10 vendors
SELECT v.Vendor_name, f.Vendor_id, round(SUM(ABS(f.Amount)),2) AS Total_Payroll_Received FROM Financial_Transactions f
LEFT JOIN Vendors v ON f.Vendor_id = v.Vendor_id WHERE f.Account_type = 'Expense' AND f.Category = 'Payroll'
GROUP BY v.Vendor_name, f.Vendor_id ORDER BY Total_Payroll_Received DESC LIMIT 10;

### Top 10 customers
select c.customer_id, c.customer_name, round(sum(f.amount),2) as Total_rev from financial_transactions f
join customers c on f.Customer_id = c.Customer_id where f.Account_type = 'Revenue' group by c.customer_id,
c.customer_name order by Total_rev desc limit 10;

with customer_revenue as(
select c.customer_id, c.customer_name, sum(f.amount) as total_revenue from financial_transactions f
join customers c on f.customer_id = c.customer_id where f.account_type = 'Revenue' group by
c.customer_id, c.customer_name),
Ranked_revenue as (select customer_id, customer_name, total_revenue, sum(total_revenue) over 
(order by total_revenue desc) as cumulative_revenue, sum(total_revenue) over () as grand_total_revenue
from customer_revenue)
SELECT Customer_name, Customer_id, Total_Revenue, Cumulative_Revenue,
ROUND((Cumulative_Revenue / Grand_Total_Revenue) * 100, 2) AS Cumulative_Percentage
FROM Ranked_Revenue ORDER BY Total_Revenue DESC;
